bump skia to fb28cd2b13d76c324570341e1155aaadc1b532b6

diff --git a/deps/skia/platform_tools/android/bin/android_gdbserver b/deps/skia/platform_tools/android/bin/android_gdbserver
--- a/deps/skia/platform_tools/android/bin/android_gdbserver
+++ b/deps/skia/platform_tools/android/bin/android_gdbserver
@@ -3,56 +3,82 @@
 # android_gdbserver: Pushes gdbserver. Starts debugging environment.
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-APP_NAME=$(basename $1)
-PORT=5039
-
-# Collect extra arguments to be passed to the Skia binary
-shift
-while (( "$#" )); do
-  APP_ARGS="$APP_ARGS $1"
-  shift
-done
-
 source $SCRIPT_DIR/android_setup.sh
 source $SCRIPT_DIR/utils/setup_adb.sh
 
+APP_NAME=${APP_ARGS[0]}
+PORT=5039
+
+BUILD_DIR="${SKIA_OUT}/${BUILDTYPE}"
+TARGET_LIBRARY="${BUILD_DIR}/lib/lib${APP_NAME}.so"
+if [ ! -f "$TARGET_LIBRARY" ]
+then
+  echo "Unable to find the ${APP_NAME} library at ${TARGET_LIBRARY}."
+  exit 1
+fi
+
 # We need the debug symbols from these files
-GDB_TMP_DIR=$(pwd)/android_gdb_tmp
-mkdir $GDB_TMP_DIR
+GDB_TMP_DIR=$SKIA_OUT/android_gdb_tmp
+mkdir -p $GDB_TMP_DIR
+
 echo "Copying symbol files"
-adb_pull_if_needed /system/bin/skia_launcher $GDB_TMP_DIR
-adb_pull_if_needed /system/lib/libc.so $GDB_TMP_DIR
-adb_pull_if_needed /data/data/com.skia/lib/libskia_android.so $GDB_TMP_DIR
-adb_pull_if_needed /data/data/com.skia/lib/lib$APP_NAME.so $GDB_TMP_DIR
+if [[ $ANDROID_ARCH == *64* ]]; then
+  SYSTEM_LIBRARY_PATH=/system/lib64
+else
+  SYSTEM_LIBRARY_PATH=/system/lib
+fi
+for library_file in \
+    libc.so \
+    libc++.so \
+    libstdc++.so \
+    libm.so \
+    liblog.so \
+    libz.so \
+    libgccdemangle.so \
+    libsigchain.so \
+    libcutils.so \
+    libunwind.so \
+    libunwind-ptrace.so \
+    libbacktrace.so \
+    libutils.so \
+    libstlport.so \
+    libGLES_trace.so \
+    libEGL.so \
+    libGLESv2.so \
+    ; do
+    ANDROID_LS=`$ADB $DEVICE_SERIAL shell ls -ld ${SYSTEM_LIBRARY_PATH}/${library_file}`
+    if [ "${ANDROID_LS:0:1}" == "-" ]; then
+      adb_pull_if_needed "${SYSTEM_LIBRARY_PATH}/${library_file}" $GDB_TMP_DIR
+    fi
+done
 
-echo "Checking for skia_launcher app..."
-if [ ! -f $GDB_TMP_DIR/skia_launcher ]
-then
-    echo "Unable for find the skia_launcher on the device"
-    rm -rf $GDB_TMP_DIR
-    exit 1;
+if [[ $ANDROID_ARCH == *64* ]]; then
+  adb_pull_if_needed /system/bin/linker64 $GDB_TMP_DIR
+else
+  adb_pull_if_needed /system/bin/linker $GDB_TMP_DIR
 fi
 
-echo "Checking for $APP_NAME library..."
-if [ ! -f $GDB_TMP_DIR/lib$APP_NAME.so ]
-then
-    echo "Unable for find the app's shared library on the device"
-    rm -rf $GDB_TMP_DIR
-    exit 1;
-fi
+echo "Pushing app..."
+for file in \
+    "${BUILD_DIR}/skia_launcher" \
+    "${BUILD_DIR}/lib/libskia_android.so" \
+    "${BUILD_DIR}/lib/lib${APP_NAME}.so" \
+    ; do
+    cp "$file" $GDB_TMP_DIR
+    adb_push_if_needed "$file" /data/local/tmp
+done
 
 echo "Pushing gdbserver..."
-$ADB remount
-$ADB push $ANDROID_TOOLCHAIN/../gdbserver /system/bin/gdbserver
+adb_push_if_needed $ANDROID_TOOLCHAIN/../gdbserver /data/local/tmp
 
 echo "Setting up port forward"
 $ADB forward "tcp:5039" "tcp:5039"
 
-# Kill all previous instances of gdbserver and skia_launcher to rid all port overriding errors.
+# Kill all previous instances of gdbserver and the app to rid all port overriding errors.
 echo "Killing any running Skia processes."
 $ADB shell ps | grep gdbserver | awk '{print $2}' | xargs $ADB shell kill
-$ADB shell ps | grep skia_launcher | awk '{print $2}' | xargs $ADB shell kill
+$ADB shell ps | grep ${APP_NAME} | awk '{print $2}' | xargs $ADB shell kill
 
 # Starting up gdbserver in android shell
-echo "Starting gdbserver with command: skia_launcher $APP_NAME$APP_ARGS"
-$ADB shell gdbserver :5039 /system/bin/skia_launcher $APP_NAME$APP_ARGS & 
+echo "Starting gdbserver with command: ${APP_ARGS[@]}"
+$ADB shell LD_LIBRARY_PATH=/data/local/tmp:\$LD_LIBRARY_PATH /data/local/tmp/gdbserver :5039 /data/local/tmp/skia_launcher ${APP_ARGS[@]} &
diff --git a/deps/skia/platform_tools/android/bin/android_run_skia b/deps/skia/platform_tools/android/bin/android_run_skia
--- a/deps/skia/platform_tools/android/bin/android_run_skia
+++ b/deps/skia/platform_tools/android/bin/android_run_skia
@@ -4,45 +4,69 @@
 # output, and kills the app if interrupted.
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
+source $SCRIPT_DIR/android_setup.sh
 source $SCRIPT_DIR/utils/setup_adb.sh
 
-APP_ARGS=""
-USE_INTENT="false"
-SERIAL=""
-
-while (( "$#" )); do
-
-  if [[ "$1" == "--intent" ]];
-  then
-    USE_INTENT="true"
-  elif [[ "$1" == "-s" ]];
-  then
-    if [[ $# -lt 2 ]];
-    then
-      echo "ERROR: missing serial number"
-      exit 1;
-    fi
-    SERIAL="-s $2"
-    shift
-  else
-    APP_ARGS="$APP_ARGS $1"
-  fi
-
-shift
-done
-
-
-if [[ "$USE_INTENT" == "true" ]];
+if [ ! -f "${SKIA_OUT}/$BUILDTYPE/lib/lib${APP_ARGS[0]}.so" ];
 then
-    $ADB $SERIAL logcat -c
-    $ADB $SERIAL shell am broadcast -a com.skia.intent.action.LAUNCH_SKIA -n com.skia/.SkiaReceiver -e args "$APP_ARGS"
-    trap "echo \"Interrupt.\"" INT
-    eval "($ADB $SERIAL logcat)"
-    trap - INT
-    echo "Interrupt. Killing Skia process..."
-    $SCRIPT_DIR/android_kill_skia $SERIAL
-    echo "Done."
-else
-    $ADB $SERIAL shell skia_launcher $APP_ARGS
+  echo "Unable to find $BUILDTYPE ${APP_ARGS[0]} library"
+  exit 1
 fi
+
+verbose "pushing binaries onto the device..."
+adb_push_if_needed "${SKIA_OUT}/$BUILDTYPE/skia_launcher" /data/local/tmp
+if [ -f "${SKIA_OUT}/$BUILDTYPE/lib/libskia_android.so" ]; then
+    # Does not exist for builds with static skia.
+    adb_push_if_needed "${SKIA_OUT}/$BUILDTYPE/lib/libskia_android.so" /data/local/tmp
+fi
+adb_push_if_needed "${SKIA_OUT}/$BUILDTYPE/lib/lib${APP_ARGS[0]}.so" /data/local/tmp
+if [[ -n $RESOURCE_PATH ]]; then
+  verbose "pushing resources onto the device..."
+  adb_push_if_needed "${SKIA_SRC_DIR}/resources" $RESOURCE_PATH
+fi
+
+if [ $LOGCAT ]; then
+   verbose "clearing the device logs..." 
+  $ADB $DEVICE_SERIAL logcat -c;
+fi
+STATUS_FILENAME="/data/local/tmp/.skia_tmp_$(date +%s%N)"
+CMD_FILENAME=".skia_cmd_tmp_$(date +%s%N)"
+echo "LD_LIBRARY_PATH=/data/local/tmp:$LD_LIBRARY_PATH \
+     /data/local/tmp/skia_launcher ${APP_ARGS[*]}; \
+     echo \$? > ${STATUS_FILENAME}" > ${CMD_FILENAME}
+chmod +x ${CMD_FILENAME}
+verbose "======== To reproduce this run: ========"
+verbose "android_run_skia ${APP_ARGS[*]}"
+verbose "========================================"
+verbose "pushing command file onto the device..."
+$ADB ${DEVICE_SERIAL} push ${CMD_FILENAME} /data/local/tmp
+rm ${CMD_FILENAME}
+verbose "preparing to run ${APP_ARGS[0]} on the device..."
+$ADB ${DEVICE_SERIAL} shell sh /data/local/tmp/${CMD_FILENAME}
+    
+if [ -z "$($ADB $DEVICE_SERIAL shell 'if [ -f $STATUS_FILENAME ]; then echo exists; fi')" ]; then
+  if [ $LOGCAT ]; then $ADB $DEVICE_SERIAL logcat -d; fi
+  echo "***********************************************************************"
+  echo "The application terminated unexpectedly and did not produce an exit code"
+  echo "***********************************************************************"
+  exit 1
+fi
+
+EXIT_CODE=`$ADB ${DEVICE_SERIAL} shell cat ${STATUS_FILENAME}`
+$ADB ${DEVICE_SERIAL} shell rm -f ${STATUS_FILENAME} ${CMD_FILENAME}
+
+# check to see if the 'cat' command failed and print errors accordingly
+if [[ ${EXIT_CODE} == *${STATUS_FILENAME}* ]]; then
+  if [ $LOGCAT ]; then $ADB $DEVICE_SERIAL logcat -d; fi
+  echo "***********************************************************************"
+  echo "ADB failed to retrieve the application's exit code"
+  echo "***********************************************************************"
+  exit 1
+fi
+
+echo "EXIT_CODE is ${EXIT_CODE}"
+if [ $'0\r' != "${EXIT_CODE}" ]; then
+  if [ $LOGCAT ]; then $ADB $DEVICE_SERIAL logcat -d; fi
+  exit 1
+fi
+exit 0
